pipeline:
  build:
    image: tuetuopay/qt5:${DIST}-${CXX}
    commands:
      - cd pinkie-card
      - qmake-qt5 || qmake
      - make -j8 CXX=$(echo ${CXX} | sed s/cc//g)++

  telegram:
    image: tuetuopay/drone-telegram
    token: ${TGBOT_TOKEN}
    to:
      - "-172113772"
    append: "on ${DIST} with ${CXX}"

matrix:
  DIST:
    - arch
    - fedora
    - ubuntu
  CXX:
    - gcc
    - clang

