pipeline:
  build:
    image: tuetuopay/qt5
    commands:
      - pushd pinkie-card
      - qmake-qt5 -project
      - echo "QT += qml" >> pinkie-card.pro
      - qmake-qt5
      - make -j8

  telegram:
    image: appleboy/drone-telegram
    token: ${TGBOT_TOKEN}
    to:
      - "-172113772"
    message: |
      {{ #success build.status }}
        Build {{ build.number }} succeeded. Yay to {{ build.author }}!
      {{ else }}
        Build {{ build.number }} failed. {{ build.author }} YOU SUCK!
      {{ /success }}

