pipeline:
  build:
    image: tuetuopay/qt5
    commands:
      - pushd pinkie-card
      - qmake-qt5
      - make -j8

  report:
    image: blang/latex
    commands:
      - pushd report
      - pdflatex report.tex

  telegram:
    image: appleboy/drone-telegram
    token: ${TGBOT_TOKEN}
    to:
      - "-172113772"
    document:
      - report/report.pdf
    message: |
      {{ build.author }}: {{ build.commit }}
      Build {{ build.number }} {{ build.status }}.

